// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AsyncAPIApplication.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AsyncAPIApplication.CompiledModels
{
    public static class ListOfRequestsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ListOfRequests @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EstimatedTimeToCompleteTheTask>k__BackingField")]
        public static extern ref string EstimatedTimeToCompleteTheTask(ListOfRequests @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RequestBody>k__BackingField")]
        public static extern ref string RequestBody(ListOfRequests @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RequestId>k__BackingField")]
        public static extern ref string RequestId(ListOfRequests @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StatusOfRequest>k__BackingField")]
        public static extern ref string StatusOfRequest(ListOfRequests @this);
    }
}
