@AsyncAPIApplication_HostAddress = http://localhost:5185

GET {{AsyncAPIApplication_HostAddress}}/todos/
Accept: application/json

###

GET {{AsyncAPIApplication_HostAddress}}/todos/1
Accept: application/json

###
